# Server settings
server:
    port: 8084

# SPRING PROFILES
spring:
    datasource:
#      url: jdbc:mysql://127.0.0.1:3306/shiro?useUnicode=true&characterEncoding=utf-8&useSSL=false
#      driver-class-name: com.mysql.jdbc.Driver
#      username: root
#      password: 123456
#      type: com.alibaba.druid.pool.DruidDataSource
#      url: jdbc:mysql://172.20.8.32:3306/dudu_ops?useUnicode=true&characterEncoding=utf-8&useSSL=false
#      driver-class-name: com.mysql.jdbc.Driver
#      username: duduops
#      password: duduops_2017
      type: com.alibaba.druid.pool.DruidDataSource
      url: jdbc:mysql://172.20.8.242:3306/dudu_ops?useUnicode=true&characterEncoding=utf-8&useSSL=false&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true
      driver-class-name: com.mysql.jdbc.Driver
      username: root
      password: root
#      type: com.alibaba.druid.pool.DruidDataSource
#      url: jdbc:mysql://172.20.8.244:9596/dudu_ops?useUnicode=true&characterEncoding=utf-8&useSSL=false
#      driver-class-name: com.mysql.jdbc.Driver
#      username: dudu_ops
#      password: yytxops2017
    jpa:
      show-sql: true
    # HTTP ENCODING
    http:
        encoding.charset: UTF-8
        encoding.enable: true
        encoding.force: true
        multipart.maxFileSize: 10Mb
    #Redis
    redis:
      host: 172.20.14.223
      port: 6379
      password: yytx!2018
      # 连接池中的最大空闲连接
      pool.max-idle: 10
      # 连接池中的最小空闲连接
#      pool.min-idle: 1
      # 连接池最大连接数（使用负值表示没有限制）
      pool.max-active: 10
      # 连接池最大阻塞等待时间（使用负值表示没有限制）
      pool.max-wait: 20000
      # 连接超时时间（毫秒）
      timeout: 20000
#c3p0:
#  jdbcUrl: jdbc:mysql://127.0.0.1:3306/dudu_cass?useUnicode=true&characterEncoding=utf-8&useSSL=false
#  user: ${db.username:root}
#  password: ${db.password:123456}
#  driverClass: com.mysql.jdbc.Driver
#  minPoolSize: 2
#  maxPoolSize: 10
#  maxIdleTime: 1800000
#  acquireIncrement: 3
#  maxStatements: 1000
#  initialPoolSize: 3
#  idleConnectionTestPeriod: 60
#  acquireRetryAttempts: 30
#  acquireRetryDelay: 1000
#  breakAfterAcquireFailure: false
#  testConnectionOnCheckout: false

# MyBatis
mybatis:
    mapper-locations: classpath:/mappings/*.xml
    type-aliases-package: dudu.ops.managerger
    configuration.mapUnderscoreToCamelCase: true
    #configLocation: classpath:/mybatis-config.xml
mapper:
    mappers: dudu.ops.manager.auth.util.MyMapper
    not-empty: false
    identity: MYSQL
pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count\=countSql



# LOGGING
logging:
    file: ${spring.application.name}.log
    level:
       com.ibatis: DEBUG
       dudu.ops: DEBUG
