spring:
  application:
    name: yak-eureka
server:
  port: 8711
eureka:
  instance:
    hostname: 123.57.145.164
  client:
    register-with-eureka: false
    fetch-registry: false
    serviceUrl:
      defaultZone: http://123.57.145.164:${server.port}/eureka/


#123.57.145.164

