spring:
    application:
        name: yak-eureka
    profiles:
        active: localhost
# LOGGING
logging:
    file: ../logs/${spring.application.name}.log
    level:
    root: WARN
---
spring:
    profiles: localhost
server:
    port: 8711
eureka:
    client:
        register-with-eureka: false
        fetch-registry: false
        serviceUrl:
            defaultZone: http://localhost:8711/eureka/
   

