spring:
    application:
        name: yak-eureka
    profiles:
        active: server
# LOGGING
logging:
    file: ../../logs/${spring.application.name}.log
    level:
    root: WARN
---
spring:
    profiles: server
server:
    port: 8711
eureka:
    instance:
        hostname: ${spring.cloud.client.ipAddress}
    client:
        #由于该应用为注册中心,所以设置为false,代表不向注册中心注册自己
        register-with-eureka: false
        #由于注册中心的职责就是维护服务实例,它并不需要去检索服务,所以也设置为false
        fetch-registry: false
        serviceUrl:
            defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
   

