spring:
  application:
    name: yak-config
  profiles:
    active: pro
---
spring:
  profiles: pro
  cloud:
    config:
      server:
        git:
          uri: http://git.yonyoutelecom.cn/duducloud/yak-config.git
          username: ${config.username:yangkaic@yonyou.com}
          password: ${config.password:yakyang2118}

server:
  port: 8888
  maxHttpHeaderSize: 8192

eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://${spring.cloud.client.ipAddress}:8711/eureka/

